version: "3.9"
services:
  app:
      build:
        context: ./docker/php
      ports:
        - "${APP_PORT-9000}:9000" 
        - "${XDEBUG_PORT-9003}:9003"
      volumes:
        - ./:/var/www/project
      environment:
        - APP_PORT=${APP_PORT-9000}
        - XDEBUG_MODE=${XDEBUG_MODE-debug}
        - XDEBUG_CLIENT_HOST=${XDEBUG_CLIENT_HOST-host.docker.internal}
      depends_on:
        - mysql
        - redis
      networks:
        - laravel-network

  nginx:
    image: nginx:1.27-alpine
    ports:
      - "${NGINX_PORT-8080}:80"
    volumes:
      - ./:/var/www/project
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel-network

  mysql:
    image: mysql:8.4
    ports:
      - "${MYSQL_PORT-33066}:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel-network

  redis:
    image: redis:7.2-alpine
    command: redis-server --requirepass ChangeMe
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - laravel-network

volumes:
  mysql_data:

  redis_data:

networks:
  laravel-network:
    driver: bridge
